# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate indicatif

Name:           rust-%{crate}
Version:        0.17.0~beta.1
Release:        1%{?dist}
Summary:        Progress bar and cli reporting library for Rust

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/indicatif
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Progress bar and cli reporting library for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+improved_unicode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+improved_unicode-devel %{_description}

This package contains library source intended for building other packages
which use "improved_unicode" feature of "%{crate}" crate.

%files       -n %{name}+improved_unicode-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages
which use "rayon" feature of "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+unicode-segmentation-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicode-segmentation-devel %{_description}

This package contains library source intended for building other packages
which use "unicode-segmentation" feature of "%{crate}" crate.

%files       -n %{name}+unicode-segmentation-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+unicode-width-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicode-width-devel %{_description}

This package contains library source intended for building other packages
which use "unicode-width" feature of "%{crate}" crate.

%files       -n %{name}+unicode-width-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+with_rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with_rayon-devel %{_description}

This package contains library source intended for building other packages
which use "with_rayon" feature of "%{crate}" crate.

%files       -n %{name}+with_rayon-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Oct 05 18:41:52 BST 2021 Alexander Manning <mail@alex-m.co.uk> - 0.17.0~beta.1-1
- Initial package
