# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/mautrix/go
%global goipath         maunium.net/go/mautrix
%global forgeurl        https://github.com/mautrix/go
%global commit          3467963a8fe821ad1c5243c3c89a036143dc7b98
Version:                0.11.1

%gometa

%global common_description %{expand:
A Golang Matrix framework.}

%global golicenses      LICENSE crypto/canonicaljson/LICENSE\\\
                        crypto/olm/LICENSE pushrules/glob/LICENSE
%global godocs          example README.md crypto/canonicaljson/README.md\\\
                        crypto/olm/README.md pushrules/glob/README.md\\\
                        util/base58/README.md

%global goextensions sql json

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Golang Matrix framework

# Upstream license specification: Apache-2.0 and MIT and MPL-2.0
License:        ASL 2.0 and MIT and MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  libolm-devel
BuildRequires:  libolm

BuildRequires:  libstdc++-devel
BuildRequires:  libstdc++
BuildRequires:  libstdc++-static

%description
%{common_description}

%gopkg

%prep
%goprep -k

#sed -i '/\/\/go:build !cgo || nocrypto/ a // +build !cgo nocrypto' bridge/no-crypto.go
#sed -i '/\/\/go:build cgo && !nocrypto/ a // +build cgo,!nocrypto' bridge/crypto.go
#sed -i '\/\/go:build cgo && !nocrypto/ a // +build cgo,!nocrypto' bridge/cryptostore.go

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d crypto
%endif

%gopkgfiles

%changelog
* Mon Jun 13 2022 Alex Manning <mail@alex-m.co.uk> - 0.11.0-1
- Initial package
