# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/tulir/maulogger
%global goipath         maunium.net/go/maulogger/v2
%global forgeurl        https://github.com/tulir/maulogger
Version:                2.3.2

%gometa

%global common_description %{expand:
A logger for Go programs.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A logger for Go programs

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Jun 13 2022 Alex Manning <mail@alex-m.co.uk> - 2.3.2-1
- Initial package
