# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/tulir/mauflag
%global goipath         maunium.net/go/mauflag
%global forgeurl        https://github.com/tulir/mauflag
Version:                1.0.0

%gometa

%global common_description %{expand:
An extendable argument parser for Golang.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        An extendable argument parser for Golang

# Upstream license specification: GPL-3.0-only
License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in flagtest; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Jun 13 2022 Alex Manning <mail@alex-m.co.uk> - 1.0.0-1
- Initial package
