# Generated by go2rpm 1.6.0
%bcond_without check

%global debug_package %{nil}

# https://github.com/tulir/whatsmeow
%global goipath         go.mau.fi/whatsmeow
%global forgeurl        https://github.com/tulir/whatsmeow
%global commit          5e6b9804193aca041471db272b9d4a9ec45a7281

%gometa

%global common_description %{expand:
Go library for the WhatsApp web multidevice API.}

%global golicenses      LICENSE
%global godocs          README.md binary/proto/extract/README.md\\\
                        mdtest/README.md

%global goextensions raw

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go library for the WhatsApp web multidevice API

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

#build
#for cmd in mdtest; do
  #gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
#done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
#install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md binary/proto/extract/README.md mdtest/README.md
#{_bindir}/*

%gopkgfiles

%changelog
* Mon Jun 13 2022 Alex Manning <mail@alex-m.co.uk> - 0-0.1.20220613gitf28d984
- Initial package
