# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate time

Name:           rust-%{crate}
Version:        0.3.0
Release:        1%{?dist}
Summary:        Date and time library

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/time
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Date and time library. Fully interoperable with the standard library. Mostly
compatible with #![no_std].}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages
which use "alloc" feature of "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+formatting-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+formatting-devel %{_description}

This package contains library source intended for building other packages
which use "formatting" feature of "%{crate}" crate.

%files       -n %{name}+formatting-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+itoa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+itoa-devel %{_description}

This package contains library source intended for building other packages
which use "itoa" feature of "%{crate}" crate.

%files       -n %{name}+itoa-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+large-dates-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+large-dates-devel %{_description}

This package contains library source intended for building other packages
which use "large-dates" feature of "%{crate}" crate.

%files       -n %{name}+large-dates-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+local-offset-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+local-offset-devel %{_description}

This package contains library source intended for building other packages
which use "local-offset" feature of "%{crate}" crate.

%files       -n %{name}+local-offset-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macros-devel %{_description}

This package contains library source intended for building other packages
which use "macros" feature of "%{crate}" crate.

%files       -n %{name}+macros-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+parsing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parsing-devel %{_description}

This package contains library source intended for building other packages
which use "parsing" feature of "%{crate}" crate.

%files       -n %{name}+parsing-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+quickcheck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quickcheck-devel %{_description}

This package contains library source intended for building other packages
which use "quickcheck" feature of "%{crate}" crate.

%files       -n %{name}+quickcheck-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+quickcheck-dep-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quickcheck-dep-devel %{_description}

This package contains library source intended for building other packages
which use "quickcheck-dep" feature of "%{crate}" crate.

%files       -n %{name}+quickcheck-dep-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages
which use "rand" feature of "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-human-readable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-human-readable-devel %{_description}

This package contains library source intended for building other packages
which use "serde-human-readable" feature of "%{crate}" crate.

%files       -n %{name}+serde-human-readable-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+time-macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-macros-devel %{_description}

This package contains library source intended for building other packages
which use "time-macros" feature of "%{crate}" crate.

%files       -n %{name}+time-macros-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Oct 05 19:03:51 BST 2021 Alexander Manning <mail@alex-m.co.uk> - 0.3.0-1
- Initial package
