# Generated by go2rpm 1.3
%bcond_without check

# This is an internet build, because go dependencies make my head hurt.
%global go_generate_buildrequires %{nil}

# https://github.com/tulir/gomuks
%global goipath         maunium.net/go/gomuks
%global forgeurl        https://github.com/tulir/gomuks
Version:                0.2.3

%global goname gomuks
%gometa

%global common_description %{expand:
A terminal based Matrix client written in Go.}

%global golicenses      LICENSE lib/ansimage/LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A terminal based Matrix client written in Go

License:        AGPL-3.0
URL:            %{gourl}
Source0:        %{gosource}

#BuildRequires:  golang(github.com/alecthomas/chroma)
#BuildRequires:  golang(github.com/alecthomas/chroma/lexers)
#BuildRequires:  golang(github.com/alecthomas/chroma/styles)
#BuildRequires:  golang(github.com/disintegration/imaging)
#BuildRequires:  golang(github.com/gabriel-vasile/mimetype)
#BuildRequires:  golang(github.com/kyokomi/emoji/v2)
#BuildRequires:  golang(github.com/lithammer/fuzzysearch/fuzzy)
#BuildRequires:  golang(github.com/lucasb-eyer/go-colorful)
#BuildRequires:  golang(github.com/mattn/go-runewidth)
#BuildRequires:  golang(github.com/mattn/go-sqlite3)
#BuildRequires:  golang(github.com/rivo/uniseg)
#BuildRequires:  golang(github.com/russross/blackfriday/v2)
#BuildRequires:  golang(github.com/sasha-s/go-deadlock)
#BuildRequires:  golang(github.com/zyedidia/clipboard)
#BuildRequires:  golang(go.etcd.io/bbolt)
#BuildRequires:  golang(golang.org/x/image/bmp)
#BuildRequires:  golang(golang.org/x/image/tiff)
#BuildRequires:  golang(golang.org/x/image/webp)
#BuildRequires:  golang(golang.org/x/net/html)
#BuildRequires:  golang(gopkg.in/vansante/go-ffprobe.v2)
#BuildRequires:  golang(gopkg.in/yaml.v2)
#BuildRequires:  golang(maunium.net/go/mautrix)
#BuildRequires:  golang(maunium.net/go/mautrix/crypto)
#BuildRequires:  golang(maunium.net/go/mautrix/crypto/attachment)
#BuildRequires:  golang(maunium.net/go/mautrix/crypto/ssss)
#BuildRequires:  golang(maunium.net/go/mautrix/event)
#BuildRequires:  golang(maunium.net/go/mautrix/format)
#BuildRequires:  golang(maunium.net/go/mautrix/id)
#BuildRequires:  golang(maunium.net/go/mautrix/pushrules)
#BuildRequires:  golang(maunium.net/go/mauview)
#BuildRequires:  golang(maunium.net/go/tcell)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%global gomodulesmode GO111MODULE=auto
%gobuild -o %{gobuilddir}/bin/gomuks %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed May 05 11:40:13 BST 2021 Alex Manning <git@alex-m.co.uk> - 0.2.3-1
- Initial package
