# Generated by rust2rpm 16
%bcond_without check
%global __cargo_skip_build 0

%global crate synapse_compress_state
%global forgeurl https://github.com/matrix-org/rust-synapse-compress-state
Version:        0.1.0
%forgemeta

Name:           rust-%{crate}
Release:        1%{?dist}
Summary:        Tool to compress some state in a Synapse instance's database

# Upstream license specification: None
License:        ASL2

URL:            %{forgeurl}
Source:         %{forgesource}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Tool to compress some state in a Synapse instance's database.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%{_bindir}/synapse_compress_state

%prep
%forgesetup
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Oct 05 12:45:41 BST 2021 Alexander Manning <mail@alex-m.co.uk> - 0.1.0-1
- Initial package
