# Generated by go2rpm 1.5.0
%bcond_without check

%global go_generate_buildrequires %{nil}

# https://github.com/matrix-org/dendrite
%global goipath         github.com/matrix-org/dendrite
Version:                0.5.0
%global tag             v%{version}

%gometa

%global common_description %{expand:
Dendrite is a second-generation Matrix homeserver written in Go!}

%global golicenses      LICENSE
%global godocs          docs README.md CHANGES.md appservice/README.md\\\
                        mediaapi/README.md syncapi/README.md\\\
                        roomserver/README.md clientapi/README.md\\\
                        cmd/goose/README.md cmd/dendrite-demo-\\\
                        yggdrasil/README.md build/docker/README.md\\\
                        build/scripts/README.md keyserver/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Dendrite is a second-generation Matrix homeserver written in Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:   git
BuildRequires:   breezy

%global gocompilerflags -mod=vendor %gocompilerflags
%global gomodulesmode GO111MODULE=auto

%if %{with check}
# Tests
BuildRequires:  golang(github.com/DATA-DOG/go-sqlmock)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep -k
cd %{_builddir}/dendrite-%{version}
go mod vendor -v

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
mkdir ./testdeps
export PATH=$PWD/testdeps:$PATH
cp /usr/bin/go-rpm-integration ./testdeps/go-rpm-integration
sed -i "s/GO111MODULE=off/GO111MODULE=auto/g" ./testdeps/go-rpm-integration
sed -i "s/GO111MODULE: off/GO111MODULE: auto/g" ./testdeps/go-rpm-integration
%gocheck
%endif

%files
%license LICENSE
%doc docs README.md CHANGES.md appservice/README.md mediaapi/README.md
%doc syncapi/README.md roomserver/README.md clientapi/README.md
%doc cmd/goose/README.md cmd/dendrite-demo-yggdrasil/README.md
%doc build/docker/README.md build/scripts/README.md keyserver/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Sep 06 2021 Alexander Manning <mail@alex-m.co.uk> - 0.5.0-1%{?dist}
- Initial package
