# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/mautrix/whatsapp
%global goipath         maunium.net/go/mautrix-whatsapp
%global forgeurl        https://github.com/mautrix/whatsapp
%global commit          43d8fc5d2bb22b6cbc90bbf102087f0929f110b8
Version:                0.4.1~rc1

%global goname mautrix-whatsapp

%gometa

%global common_description %{expand:
A Matrix-WhatsApp puppeting bridge.}

%global golicenses      LICENSE
%global godocs          ROADMAP.md CHANGELOG.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        A Matrix-WhatsApp puppeting bridge

# Upstream license specification: AGPL-3.0-only
License:        AGPLv3
URL:            %{gourl}
Source0:        %{gosource}
Source1:        mautrix-whatsapp.service

BuildRequires:  libolm-devel
BuildRequires:  libolm

BuildRequires:  libstdc++-devel
BuildRequires:  libstdc++
BuildRequires:  libstdc++-static

BuildRequires: systemd-rpm-macros

%{?systemd_requires}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/mautrix-whatsapp %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -p -D -T -m 0644 %{SOURCE1} %{buildroot}%{_unitdir}/mautrix-whatsapp.service
install -p -D -T -m 0644 %{gobuilddir}/../example-config.yaml %{buildroot}%{_sysconfdir}/mautrix/whatsapp/config.yaml

%post
%systemd_post mautrix-whatsapp.service

%preun
%systemd_preun mautrix-whatsapp.service

%postun
%systemd_postun_with_restart mautrix-whatsapp.service

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc ROADMAP.md CHANGELOG.md README.md
%{_bindir}/*

%{_unitdir}/mautrix-whatsapp.service
%attr(755,root,root) %dir %{_sysconfdir}/mautrix/whatsapp
%attr(644,root,root) %config(noreplace) %{_sysconfdir}/mautrix/whatsapp/*

%gopkgfiles

%changelog
* Mon Jun 13 2022 Alex Manning <mail@alex-m.co.uk> - 0.4.0-1
- Initial package
