# Generated by go2rpm 1.5.0
%bcond_without check

%global go_generate_buildrequires %{nil}

# https://github.com/turt2live/matrix-media-repo
%global goipath         github.com/turt2live/matrix-media-repo
Version:                1.2.8

%gometa

%global common_description %{expand:
Matrix media repository with multi-domain in mind.}

%global golicenses      LICENSE
%global godocs          docs README.md CONTRIBUTING.md CHANGELOG.md

Name:           matrix-media-repo
Release:        1%{?dist}
Summary:        Matrix media repository with multi-domain in mind

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:   git
BuildRequires:   systemd

%global gomodulesmode GO111MODULE=auto

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_libexecdir}/matrix-media-repo
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_libexecdir}/matrix-media-repo/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs README.md CONTRIBUTING.md CHANGELOG.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Sep 29 2021 Alexander Manning <mail@alex-m.co.uk> - 1.2.8-1%{?dist}
- Initial package
